/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Dao.OffreCroisiereDao;

import Dao.SendEmailDao;
import entite.Client;
import entite.Croisiere;
import entite.MAIL;
import entite.User;
import entite.panierdereservation;
import entite.recup_id;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ahmed
 */
public class Acc_Off_Crois extends javax.swing.JFrame {
    public static final String NL = System.getProperty("line.separator");

    
    
      public static int id;
    private User owner = null;
    private boolean isFact = true;
    private int cas = 0;
    /**
     * Creates new form Acc_Off_Crois
     */
    public Acc_Off_Crois() {
        initComponents();
        UpdateOffreCroisiere();
    }
    
    
    
    
    
        public void UpdateOffreCroisiere(){
        
            DefaultTableModel model =(DefaultTableModel) JtableOffreCroisiere.getModel();
            
            TableRowSorter<TableModel> rowSorter
            = new TableRowSorter<TableModel>(model);
            
           
            
            
            JtableOffreCroisiere.setRowSorter(rowSorter);
            //******************
        
        OffreCroisiereDao odao = new OffreCroisiereDao();
        Object[] rowData = new Object[12];
        
        for(int i=0;i<odao.AfficherOffreCroisiere().size();i++){
         
            rowData[0] = odao.AfficherOffreCroisiere().get(i).getIdCroisiere();
             rowData[1] = odao.AfficherOffreCroisiere().get(i).getReduction();
               rowData[2] = odao.AfficherOffreCroisiere().get(i).getNomcrois();
                rowData[3] = odao.AfficherOffreCroisiere().get(i).getPrix();
                  rowData[4] = odao.AfficherOffreCroisiere().get(i).getDate_Debut();
                   rowData[5] = odao.AfficherOffreCroisiere().get(i).getDate_Fin();
                    rowData[6] = odao.AfficherOffreCroisiere().get(i).getNombrePlace();
                     rowData[7] = odao.AfficherOffreCroisiere().get(i).getDateDepart();
                      rowData[8] = odao.AfficherOffreCroisiere().get(i).getNBJour();
                       rowData[9] = odao.AfficherOffreCroisiere().get(i).getVilleDepart();
                        rowData[10] = odao.AfficherOffreCroisiere().get(i).getVilleDestination();
                          rowData[11] = odao.AfficherOffreCroisiere().get(i).getDescription();
                model.addRow(rowData);          

             }  
                
                        jtfFilter.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jtfFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                   
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jtfFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                    
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
        
        
        
        
        
        

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Return = new javax.swing.JButton();
        anchorIcon = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labNom = new javax.swing.JLabel();
        LabPrenom = new javax.swing.JLabel();
        LabEmail = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        LabEmail1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableOffreCroisiere = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jtfFilter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resBtn = new javax.swing.JButton();
        anBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        anchorIcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anchorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Anchor.png"))); // NOI18N
        anchorIcon.setText("nombre de places");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        labNom.setBackground(new java.awt.Color(102, 255, 102));
        labNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNom.setForeground(new java.awt.Color(153, 153, 153));
        labNom.setText("jLabel1");

        LabPrenom.setBackground(new java.awt.Color(102, 255, 102));
        LabPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabPrenom.setForeground(new java.awt.Color(153, 153, 153));
        LabPrenom.setText("jLabel2");

        LabEmail.setBackground(new java.awt.Color(102, 255, 102));
        LabEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabEmail.setForeground(new java.awt.Color(153, 153, 153));
        LabEmail.setText("jLabel3");

        icon1.setBackground(new java.awt.Color(204, 204, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/def.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon1MouseExited(evt);
            }
        });

        LabEmail1.setBackground(new java.awt.Color(255, 51, 102));
        LabEmail1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabEmail1.setForeground(new java.awt.Color(255, 255, 255));
        LabEmail1.setText("jLabel3");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labNom)
                        .addGap(18, 18, 18)
                        .addComponent(LabPrenom)
                        .addGap(18, 18, 18)
                        .addComponent(LabEmail))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JtableOffreCroisiere.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JtableOffreCroisiere.setFont(new java.awt.Font("Yu Gothic Medium", 2, 11)); // NOI18N
        JtableOffreCroisiere.setForeground(new java.awt.Color(0, 0, 204));
        JtableOffreCroisiere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCroisiere", "Reduction", "NomCrois", "Prix", "DateDebut", "DateFin", "NombrePlace", "Date!depart", "NBJours", "VilleDepart", "VilleDestination", "Description"
            }
        ));
        JtableOffreCroisiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableOffreCroisiereMouseClicked(evt);
            }
        });
        JtableOffreCroisiere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtableOffreCroisiereKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtableOffreCroisiere);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "search :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(240, 240, 240));

        jtfFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFilterKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jtfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        resBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1462985510_check.png"))); // NOI18N
        resBtn.setText("Reserver");
        resBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBtnActionPerformed(evt);
            }
        });

        anBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/close.png"))); // NOI18N
        anBtn.setText("Annuler");
        anBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(anchorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(resBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anchorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked

    }//GEN-LAST:event_icon1MouseClicked

    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
        icon1.setSize(icon1.getSize().width - 10, icon1.getSize().height - 10);
    }//GEN-LAST:event_icon1MouseEntered

    private void icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseExited
        icon1.setSize(icon1.getSize().width + 10, icon1.getSize().height + 10);
    }//GEN-LAST:event_icon1MouseExited

    private void JtableOffreCroisiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableOffreCroisiereMouseClicked

        DefaultTableModel model =(DefaultTableModel) JtableOffreCroisiere.getModel();

     
    }//GEN-LAST:event_JtableOffreCroisiereMouseClicked

    private void JtableOffreCroisiereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtableOffreCroisiereKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP )
        {
            DefaultTableModel model =(DefaultTableModel) JtableOffreCroisiere.getModel();

//            JTextReduction.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 1).toString());
//            jTextnomcroisiere.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 2).toString());
//
//            jTextPrix.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 3).toString());
//
//            jDateChooser1.setDate((Date) model.getValueAt(JtableOffreCroisiere.getSelectedRow(),4));
//            jDateChooser2.setDate((Date) model.getValueAt(JtableOffreCroisiere.getSelectedRow(),5));
//
//            jTextnombreplace.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 6).toString());
//            jTextdatedepart.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 7).toString());
//            jTextnombrejour.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 8).toString());
//            jTextvilledepart.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 9).toString());
//            jTextvilledestination.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 10).toString());
//
//            jTextdesc.setText(model.getValueAt(JtableOffreCroisiere.getSelectedRow(), 11).toString());
        }
    }//GEN-LAST:event_JtableOffreCroisiereKeyPressed

    private void jtfFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFilterKeyReleased

        //nklnlnlmknlknklnlk
    }//GEN-LAST:event_jtfFilterKeyReleased

    private void resBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBtnActionPerformed

        recup_id.getCl().getEmail();
        jLabel2.setText(recup_id.getCl().getEmail());
         if (JtableOffreCroisiere.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner une croisiere   !!");
        } else {
             MAIL m = new MAIL();
              m.setMail_client( recup_id.getCl().getEmail());
              
              m.setContenu("Cher Client,"+recup_id.getCl().getNom()+NL+NL
                            + " l'équipe GoVoyage vous souhaite la bienvenue !"+NL
                            +"On souhaite également vous informer de vos paramètre de connexion"+NL+NL
                            + "votre login est : "+NL
                            +"votre mot de passe est : "+NL+NL
                            +"Rendez-vous sur l'application si vous souhaitez changer de mot de passe"+NL+NL+NL+NL
                            +"L'équipe ALL FOR DEAL");
                    m.setSubject("Bienvenu");
             
                    SendEmailDao sd = new SendEmailDao();
                    sd.send2_client(m);
                   
             
               }

    }//GEN-LAST:event_resBtnActionPerformed

    private void anBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anBtnActionPerformed

      
        if (JtableOffreCroisiere.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner une croisiere   !!");
        } else {
   
             
                panierdereservation panier = new panierdereservation();
                
                
            // JtableOffreCroisiere.getModel().getValueAt(JtableOffreCroisiere.getSelectedRow(), 5);
        }
               
//                panier.setIdCroisiere(croi);
//                panier.setIdclient(owner);
//
//                if (cdao.AnnulerReservation(panier)) {
//                    cdao.reserver(croi);
//                    jTable1.setModel(new CroisierModel(cdao.afficherCroisiereByUser(owner.getId())));
//                    JOptionPane.showMessageDialog(null, "reservation annulée avec succé");
//                    txtSearch.setText("");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Erreur");
//                }
//
//            } else if (cas == 2) {
//                panierdereservation panier = new panierdereservation();
//                Hotel croi = (Hotel) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5);
//                HotelDAO cdao = new HotelDAO();
//
//                panier.setHotel(croi);
//                panier.setIdclient(owner);
//
//                if (cdao.AnnulerReservationHotel(panier)) {
//                    cdao.reserver(croi);
//                    jTable1.setModel(new ResHotelModel(cdao.afficherHotelParUser(owner.getId())));
//                    JOptionPane.showMessageDialog(null, "reservation annulée avec succé");
//                    txtSearch.setText("");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Erreur");
//                }
//
         

        
    }//GEN-LAST:event_anBtnActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

    }//GEN-LAST:event_txtSearchKeyReleased

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed

        Accueil_Offres ac = new Accueil_Offres();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acc_Off_Crois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acc_Off_Crois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acc_Off_Crois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acc_Off_Crois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acc_Off_Crois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableOffreCroisiere;
    private javax.swing.JLabel LabEmail;
    private javax.swing.JLabel LabEmail1;
    private javax.swing.JLabel LabPrenom;
    private javax.swing.JButton Return;
    private javax.swing.JButton anBtn;
    private javax.swing.JLabel anchorIcon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfFilter;
    private javax.swing.JLabel labNom;
    private javax.swing.JButton resBtn;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
