/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author ahmed
 */
public class Accueil_Offres extends javax.swing.JFrame {

    /**
     * Creates new form Accueil_Offres
     */
    public Accueil_Offres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labNom = new javax.swing.JLabel();
        LabPrenom = new javax.swing.JLabel();
        LabEmail = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        LabEmail1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Offre_Vol1 = new javax.swing.JButton();
        Offre_Vol2 = new javax.swing.JButton();
        Offre_Vol = new javax.swing.JButton();
        Return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        labNom.setBackground(new java.awt.Color(102, 255, 102));
        labNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNom.setForeground(new java.awt.Color(153, 153, 153));
        labNom.setText("jLabel1");

        LabPrenom.setBackground(new java.awt.Color(102, 255, 102));
        LabPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabPrenom.setForeground(new java.awt.Color(153, 153, 153));
        LabPrenom.setText("jLabel2");

        LabEmail.setBackground(new java.awt.Color(102, 255, 102));
        LabEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabEmail.setForeground(new java.awt.Color(153, 153, 153));
        LabEmail.setText("jLabel3");

        icon1.setBackground(new java.awt.Color(204, 204, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/def.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon1MouseExited(evt);
            }
        });

        LabEmail1.setBackground(new java.awt.Color(255, 51, 102));
        LabEmail1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabEmail1.setForeground(new java.awt.Color(255, 255, 255));
        LabEmail1.setText("jLabel3");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labNom)
                        .addGap(18, 18, 18)
                        .addComponent(LabPrenom)
                        .addGap(18, 18, 18)
                        .addComponent(LabEmail))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Offre_Vol1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Vol1.setForeground(new java.awt.Color(255, 0, 0));
        Offre_Vol1.setText("Nos Offres Croisiere");
        Offre_Vol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_Vol1ActionPerformed(evt);
            }
        });

        Offre_Vol2.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Vol2.setForeground(new java.awt.Color(255, 0, 0));
        Offre_Vol2.setText("Nos Offres Vols");
        Offre_Vol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_Vol2ActionPerformed(evt);
            }
        });

        Offre_Vol.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Vol.setForeground(new java.awt.Color(255, 0, 0));
        Offre_Vol.setText("Nos Offres Hotels");
        Offre_Vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_VolActionPerformed(evt);
            }
        });

        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Offre_Vol1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Offre_Vol2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Offre_Vol, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(271, 271, 271))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Offre_Vol1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Offre_Vol2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Offre_Vol, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked

    }//GEN-LAST:event_icon1MouseClicked

    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
        icon1.setSize(icon1.getSize().width - 10, icon1.getSize().height - 10);
    }//GEN-LAST:event_icon1MouseEntered

    private void icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseExited
        icon1.setSize(icon1.getSize().width + 10, icon1.getSize().height + 10);
    }//GEN-LAST:event_icon1MouseExited

    private void Offre_Vol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_Vol1ActionPerformed
           Acc_Off_Crois ac = new Acc_Off_Crois();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Offre_Vol1ActionPerformed

    private void Offre_Vol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_Vol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Offre_Vol2ActionPerformed

    private void Offre_VolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_VolActionPerformed

        OffreVol_Gui ac = new OffreVol_Gui();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Offre_VolActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed

           Accueil ac = new Accueil();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Offres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabEmail;
    private javax.swing.JLabel LabEmail1;
    private javax.swing.JLabel LabPrenom;
    private javax.swing.JButton Offre_Vol;
    private javax.swing.JButton Offre_Vol1;
    private javax.swing.JButton Offre_Vol2;
    private javax.swing.JButton Return;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labNom;
    // End of variables declaration//GEN-END:variables
}
