/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import entite.Client;

/**
 *
 * @author ahmed
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

     public Accueil(Client owner) {
        initComponents();
       
        

    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labNom = new javax.swing.JLabel();
        LabPrenom = new javax.swing.JLabel();
        LabEmail = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        LabEmail1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labHotels = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        labNom.setBackground(new java.awt.Color(102, 255, 102));
        labNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNom.setForeground(new java.awt.Color(153, 153, 153));
        labNom.setText("jLabel1");

        LabPrenom.setBackground(new java.awt.Color(102, 255, 102));
        LabPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabPrenom.setForeground(new java.awt.Color(153, 153, 153));
        LabPrenom.setText("jLabel2");

        LabEmail.setBackground(new java.awt.Color(102, 255, 102));
        LabEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabEmail.setForeground(new java.awt.Color(153, 153, 153));
        LabEmail.setText("jLabel3");

        icon1.setBackground(new java.awt.Color(204, 204, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/def.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon1MouseExited(evt);
            }
        });

        LabEmail1.setBackground(new java.awt.Color(255, 51, 102));
        LabEmail1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabEmail1.setForeground(new java.awt.Color(255, 255, 255));
        LabEmail1.setText("jLabel3");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labNom)
                        .addGap(18, 18, 18)
                        .addComponent(LabPrenom)
                        .addGap(18, 18, 18)
                        .addComponent(LabEmail))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1463162505_location_map_directions_geography_gps.png"))); // NOI18N
        jButton2.setText("Map");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1463162512_chart-pie.png"))); // NOI18N
        jButton4.setText("Barshart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1463162104_barchart.png"))); // NOI18N
        jButton3.setText("PieShart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Offre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Publication");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1463083969_cruise.png"))); // NOI18N
        jLabel2.setText("Mes Reservations");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        labHotels.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labHotels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Hotel.png"))); // NOI18N
        labHotels.setText("Mes Reservations");
        labHotels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHotelsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(labHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked

     

    }//GEN-LAST:event_icon1MouseClicked

    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
        icon1.setSize(icon1.getSize().width - 10, icon1.getSize().height - 10);
    }//GEN-LAST:event_icon1MouseEntered

    private void icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseExited
        icon1.setSize(icon1.getSize().width + 10, icon1.getSize().height + 10);
    }//GEN-LAST:event_icon1MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        
          new Accueil_Offres().setVisible(true);
               this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
          new Accueil_Publications().setVisible(true);
               this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

//        if (jLabel2.getText().equals("Mes Reservations")) {
//            CroisiereDAO ccdao = new CroisiereDAO();
//            jTable1.setModel(new CroisierModel(ccdao.afficherCroisiereByUser(owner.getId())));
//            System.out.println(owner);
//            jLabel2.setText("Tous Les Offres");
//            cas = 0;
//            txtSearch.setVisible(false);
//            anchorIcon.setVisible(false);
//            LabEmail1.setText("Croisieres - Mes Reservations");
//            anBtn.setEnabled(true);
//            resBtn.setEnabled(false);
//
//        } else if (jLabel2.getText().equals("Tous Les Offres")) {
//            jTable1.setModel(new CroisierModel());
//            jLabel2.setText("Mes Reservations");
//            cas = 1;
//            txtSearch.setVisible(true);
//            anchorIcon.setVisible(true);
//            LabEmail1.setText("Croisieres");
//            anBtn.setEnabled(false);
//            resBtn.setEnabled(true);
        //}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
///
    }//GEN-LAST:event_jLabel2KeyPressed

    private void labHotelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHotelsMouseClicked

//        if (labHotels.getText().equals("Mes Reservations")) {
//            HotelDAO hdao = new HotelDAO();
//            jTable1.setModel(new ResHotelModel(hdao.afficherHotelParUser(owner.getId())));
//            System.out.println(owner);
//            labHotels.setText("Tous Les Offres");
//            cas = 2;
//            txtSearch.setVisible(false);
//            anchorIcon.setVisible(false);
//            LabEmail1.setText("Hotels - Mes Reservations");
//            anBtn.setEnabled(true);
//            resBtn.setEnabled(false);
//        } else if (labHotels.getText().equals("Tous Les Offres")) {
//            jTable1.setModel(new ResHotelModel());
//            labHotels.setText("Mes Reservations");
//            cas = 3;
//            txtSearch.setVisible(true);
//            anchorIcon.setVisible(true);
//            LabEmail1.setText("Hotels");
//            anBtn.setEnabled(false);
//            resBtn.setEnabled(true);
//        }
//        System.out.println(cas + "--------");
    }//GEN-LAST:event_labHotelsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

//        BarChart b;
//        try {
//            b = new BarChart("");
//            b.setVisible(true);
//            b.setSize(500, 500);
//            b.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        } catch (IOException ex) {
//            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

//        PieChart pie = new PieChart(owner.getId());
//        pie.setVisible(true);
//        pie.setSize(500, 500);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        if (jTable1.getSelectedRow() < 0) {
//            JOptionPane.showMessageDialog(null, "Vous devez selectionner une croisiere   !!");
//        } else {
//            if (cas == 0) {
//                Croisiere croi = (Croisiere) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5);
//                System.out.println(croi);
//                if (jTable1.getSelectedRow() < 0) {
//                    JOptionPane.showMessageDialog(rootPane, "Vous devez selectionner un client", "Echec", JOptionPane.ERROR_MESSAGE);
//                } else {
//
//                }
//            }
//            if (cas == 3) {
//                panierdereservation panier = new panierdereservation();
//                Hotel croi = (Hotel) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5);
//                System.out.println(croi);
//                JFrame frame = new JFrame();
//                frame.setSize(500, 500);
//                frame.setVisible(true);
//                JPanel panMap = new JPanel();
//                panMap.setSize(500, 500);
//                try {
//                    Image image = null;
//                    URL url = new URL("http://maps.google.com/maps/api/staticmap?"
//                        + "size=500x500&"
//                        + "center=" + croi.getPaysHotel() + "," + croi.getVilleHotel()
//                        + "&key=AIzaSyCJJ4-lRUtV1HDwaF1uinFgVvPdwT5ZKU0");
//                    image = ImageIO.read(url);
//                    JLabel jbt = new JLabel();
//                    jbt.setSize(500, 500);
//                    jbt.setLocation(0, 0);
//                    jbt.setIcon(new ImageIcon(image));
//                    panMap.add(jbt);
//                    //maps.setVisible(true)
//                    ;
//                    frame.add(jbt);
//                } catch (Exception ex) {
//
//                }
//            }
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabEmail;
    private javax.swing.JLabel LabEmail1;
    private javax.swing.JLabel LabPrenom;
    private javax.swing.JLabel icon1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labHotels;
    private javax.swing.JLabel labNom;
    // End of variables declaration//GEN-END:variables
}
