/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author ahmed
 */
public class home_offre extends javax.swing.JFrame {

    /**
     * Creates new form home_offre
     */
    public home_offre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Offre_Hotel = new javax.swing.JButton();
        Offre_Vol = new javax.swing.JButton();
        Offre_Croisiere = new javax.swing.JButton();
        Retour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Offre_Hotel.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Hotel.setText("Gerer Offre Hotel");
        Offre_Hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_HotelActionPerformed(evt);
            }
        });
        getContentPane().add(Offre_Hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 350, 100));

        Offre_Vol.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Vol.setText("Gerer Offre Vol");
        Offre_Vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_VolActionPerformed(evt);
            }
        });
        getContentPane().add(Offre_Vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 350, 100));

        Offre_Croisiere.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        Offre_Croisiere.setText("Gerer Offre Croisiere");
        Offre_Croisiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Offre_CroisiereActionPerformed(evt);
            }
        });
        getContentPane().add(Offre_Croisiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 350, 100));

        Retour.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        getContentPane().add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hom.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Offre_HotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_HotelActionPerformed
        
        OffreHotel_Gui ac = new OffreHotel_Gui();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Offre_HotelActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        InterfaceOffrant ac = new InterfaceOffrant();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_RetourActionPerformed

    private void Offre_CroisiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_CroisiereActionPerformed
        
        OffreCroisiere_Gui ac = new OffreCroisiere_Gui();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Offre_CroisiereActionPerformed

    private void Offre_VolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Offre_VolActionPerformed
        
         OffreVol_Gui ac = new OffreVol_Gui();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Offre_VolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_offre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Offre_Croisiere;
    private javax.swing.JButton Offre_Hotel;
    private javax.swing.JButton Offre_Vol;
    private javax.swing.JButton Retour;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
