/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation;

/**
 *
 * @author USER
 */
public class InterfaceOffrant extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceClient
     */
    public InterfaceOffrant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Publication = new javax.swing.JButton();
        Offre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Publication.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        Publication.setText("Publication");
        Publication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicationActionPerformed(evt);
            }
        });
        getContentPane().add(Publication, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 390, 80));

        Offre.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        Offre.setText("Offre");
        Offre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffreActionPerformed(evt);
            }
        });
        getContentPane().add(Offre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 390, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hom.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicationActionPerformed
        
        home_publication ac = new home_publication();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_PublicationActionPerformed

    private void OffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffreActionPerformed
        home_offre ac = new home_offre();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_OffreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceOffrant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceOffrant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceOffrant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceOffrant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceOffrant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Offre;
    private javax.swing.JButton Publication;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
