/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Dao.OffreVolDao;
import Dao.VolDao;
import entite.OffreVol;
import entite.Vol;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ahmed
 */
public class OffreVol_Gui extends javax.swing.JFrame {

    /**
     * Creates new form OffreVol_Gui
     */
    
      VolDao x = new VolDao();
    List <Vol> listevol = x.afficherVol();
    
    public OffreVol_Gui() {
        initComponents();
        fillCombo();
        UpdateOffreVol();
    }
    
    
    
      public void fillCombo()
    {
         VolDao odao = new VolDao();
         
         
         for(int i=0;i<odao.afficherVol().size();i++)
         {
              
              jComboBox1.addItem(listevol.get(i).getNomVol());
         } 
    }
      
      
      public void UpdateOffreVol(){
          
            TableRowSorter<TableModel> rowSorter
            = new TableRowSorter<>(JtableOffreVol.getModel());
            
            JtableOffreVol.setRowSorter(rowSorter);
            //******************
          
        
        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();
        OffreVolDao odao = new OffreVolDao();
        Object[] rowData = new Object[12];
        
        for(int i=0;i<odao.AfficherOffreVol().size();i++){
         
            rowData[0] = odao.AfficherOffreVol().get(i).getIdVol();
              rowData[1] = odao.AfficherOffreVol().get(i).getReduction();
                rowData[2] = odao.AfficherOffreVol().get(i).getPrix();
                  rowData[3] = odao.AfficherOffreVol().get(i).getDate_Debut();
                   rowData[4] = odao.AfficherOffreVol().get(i).getDate_Fin();
                    rowData[5] = odao.AfficherOffreVol().get(i).getNombrePlace();
                     rowData[6] = odao.AfficherOffreVol().get(i).getDateVol();
                      rowData[7] = odao.AfficherOffreVol().get(i).getPaysDestination();
                       rowData[8] = odao.AfficherOffreVol().get(i).getPaysDepart();
                         rowData[9] = odao.AfficherOffreVol().get(i).getDescription();
                           rowData[10] = odao.AfficherOffreVol().get(i).getNomVol();
                model.addRow(rowData); 
                
                 //******************
                jtfFilter.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jtfFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jtfFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
                
        }
        
        
        
        
        
        
    }
      
        void reset() {
        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();
            model.setRowCount(0);
        } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTextReduction = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextnomvol = new javax.swing.JTextField();
        jTextPrix = new javax.swing.JTextField();
        jTextnombreplace = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextdatevol = new javax.swing.JTextField();
        jTextpaysdestination = new javax.swing.JTextField();
        jTextpaysdepart = new javax.swing.JTextField();
        jTextdesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableOffreVol = new javax.swing.JTable();
        Retour = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        AjouterOffreVol = new javax.swing.JButton();
        SuupprimerOffreVol = new javax.swing.JButton();
        ModifierVol = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jtfFilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Vol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jComboBox1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox1.setMaximumRowCount(15);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Taux", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(240, 240, 240));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Réduction :");

        JTextReduction.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        JTextReduction.setForeground(new java.awt.Color(0, 153, 0));
        JTextReduction.setText("25");
        JTextReduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextReductionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(JTextReduction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextReduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 200, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Offre Vol Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel5.setText("Prix :");

        jLabel4.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel4.setText("Nom Vol :");

        jLabel6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel6.setText("Nombre Place:");

        jLabel7.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel7.setText("Date Debut :");

        jLabel8.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel8.setText("Date Fin :");

        jLabel11.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel11.setText("Pays Depart :");

        jLabel12.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel12.setText("Pays Destination :");

        jLabel13.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel13.setText("Date Vol :");

        jLabel14.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel14.setText("Description :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextnomvol, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextnombreplace, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextpaysdepart, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextdatevol, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTextpaysdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextnomvol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextdatevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextpaysdepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextpaysdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jTextdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextnombreplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 460, 250));

        JtableOffreVol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JtableOffreVol.setFont(new java.awt.Font("Yu Gothic Medium", 2, 11)); // NOI18N
        JtableOffreVol.setForeground(new java.awt.Color(0, 0, 204));
        JtableOffreVol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Reduction", "Prix", "DateDebut", "DateFin", "Nombre Place", "DateVol", "Pays Destination", "Pays Depart", "Description", "Nom Vol"
            }
        ));
        JtableOffreVol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableOffreVolMouseClicked(evt);
            }
        });
        JtableOffreVol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtableOffreVolKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtableOffreVol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 950, 160));

        Retour.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        getContentPane().add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 110, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Button", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 0, 255)), "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 36), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        AjouterOffreVol.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        AjouterOffreVol.setForeground(new java.awt.Color(51, 153, 255));
        AjouterOffreVol.setText("Ajouter");
        AjouterOffreVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterOffreVolActionPerformed(evt);
            }
        });

        SuupprimerOffreVol.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        SuupprimerOffreVol.setForeground(new java.awt.Color(51, 153, 255));
        SuupprimerOffreVol.setText("Supprimer");
        SuupprimerOffreVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuupprimerOffreVolActionPerformed(evt);
            }
        });

        ModifierVol.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ModifierVol.setForeground(new java.awt.Color(51, 153, 255));
        ModifierVol.setText("Modifier");
        ModifierVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierVolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SuupprimerOffreVol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AjouterOffreVol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifierVol, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(AjouterOffreVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModifierVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SuupprimerOffreVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 260, 230));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(240, 240, 240));

        jtfFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFilterKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jtfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture_Projet.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jTextnomvol.setText(listevol.get(jComboBox1.getSelectedIndex()).getNomVol());

        int red = Integer.parseInt(JTextReduction.getText());
        int Prixconv = listevol.get(jComboBox1.getSelectedIndex()).getPrix();
        float prixpcred = Prixconv - (Prixconv*red)/100 ;
        String f1pcp = Float.toString(prixpcred);

        jTextPrix.setText(f1pcp);

        jTextnombreplace.setText(Integer.toString(listevol.get(jComboBox1.getSelectedIndex()).getNombrePlace()));
         
        
        
        jTextpaysdestination.setText(listevol.get(jComboBox1.getSelectedIndex()).getPaysDestination());
        jTextpaysdepart.setText(listevol.get(jComboBox1.getSelectedIndex()).getPaysDepart());
        jTextdesc.setText(listevol.get(jComboBox1.getSelectedIndex()).getDescription());
        
        jTextdatevol.setText(listevol.get(jComboBox1.getSelectedIndex()).getDateVol());

        
        
        // int x = listecroisiere.get(jComboBox1.getSelectedIndex()).getNombrePlace();

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JTextReductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextReductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextReductionActionPerformed

    private void JtableOffreVolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableOffreVolMouseClicked

        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();

        JTextReduction.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 1).toString());
      
        jTextPrix.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 2).toString());

        jDateChooser1.setDate((Date) model.getValueAt(JtableOffreVol.getSelectedRow(),3));
        jDateChooser2.setDate((Date) model.getValueAt(JtableOffreVol.getSelectedRow(),4));

        jTextnombreplace.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 5).toString());
        jTextdatevol.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 6).toString());
        jTextpaysdestination.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 7).toString());
        jTextpaysdepart.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 8).toString());
        

        jTextdesc.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 9).toString());
        
          jTextnomvol.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 10).toString());
        
    }//GEN-LAST:event_JtableOffreVolMouseClicked

    private void JtableOffreVolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtableOffreVolKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP )
        {
       DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();

        JTextReduction.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 1).toString());
      
        jTextPrix.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 2).toString());

        jDateChooser1.setDate((Date) model.getValueAt(JtableOffreVol.getSelectedRow(),3));
        jDateChooser2.setDate((Date) model.getValueAt(JtableOffreVol.getSelectedRow(),4));

        jTextnombreplace.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 5).toString());
        jTextdatevol.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 6).toString());
        jTextpaysdestination.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 7).toString());
        jTextpaysdepart.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 8).toString());
        

        jTextdesc.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 9).toString());
        
          jTextnomvol.setText(model.getValueAt(JtableOffreVol.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_JtableOffreVolKeyPressed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        home_offre ac = new home_offre();
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_RetourActionPerformed

    private void AjouterOffreVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterOffreVolActionPerformed

        java.util.Date aujourdhui = new java.util.Date();

        OffreVol o1 = new OffreVol();
        OffreVolDao odao = new OffreVolDao();

        java.sql.Date tanggalMulai = new java.sql.Date(jDateChooser1.getDate().getTime());
        java.sql.Date tanggalMulai2 = new java.sql.Date(jDateChooser2.getDate().getTime());

        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();

        if(tanggalMulai.compareTo(aujourdhui)>0 )
        {
            if(tanggalMulai.compareTo(tanggalMulai2)<0)
            {
                o1.setReduction(Integer.parseInt(JTextReduction.getText()));
                
                o1.setPrix(Float.parseFloat(jTextPrix.getText()));
                o1.setDate_Debut(tanggalMulai);
                o1.setDate_Fin(tanggalMulai2);
                o1.setNombrePlace(Integer.parseInt(jTextnombreplace.getText()));
                o1.setDateVol(jTextdatevol.getText());
                
                o1.setPaysDepart(jTextpaysdepart.getText());
                o1.setPaysDestination(jTextpaysdestination.getText());
                o1.setDescription(jTextdesc.getText());
                o1.setNomVol(jTextnomvol.getText());
                
                odao.AjouterOffreVil(o1);

                reset();
                UpdateOffreVol();

                JOptionPane.showMessageDialog(rootPane, "Offre Croisiere Ajouter");
            }else{JOptionPane.showMessageDialog(rootPane, "La 2éme Date Doit etre Apres La date Du Debut");}
        }else{JOptionPane.showMessageDialog(rootPane, "La Date Doit etre Apres La date D'Aujourdhui");}
    }//GEN-LAST:event_AjouterOffreVolActionPerformed

    private void SuupprimerOffreVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuupprimerOffreVolActionPerformed

        OffreVol o1 = new OffreVol();
        OffreVolDao odao = new OffreVolDao();
        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();

        if(JtableOffreVol.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner une Offre Hotel !!"
                ,"Message",JOptionPane.INFORMATION_MESSAGE);

        }
        else{

            odao.SupprimerOffreVol((int) JtableOffreVol.getValueAt(JtableOffreVol.getSelectedRow(),0));
            model.removeRow(JtableOffreVol.getSelectedRow());
        }
    }//GEN-LAST:event_SuupprimerOffreVolActionPerformed

    private void ModifierVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierVolActionPerformed

        OffreVol o1 = new OffreVol();
        OffreVolDao odao = new OffreVolDao();

        //lMessage2.setText("" );
        DefaultTableModel model =(DefaultTableModel) JtableOffreVol.getModel();

        java.sql.Date tanggalMulai = new java.sql.Date(jDateChooser1.getDate().getTime());
        java.sql.Date tanggalMulai2 = new java.sql.Date(jDateChooser2.getDate().getTime());

        if(JtableOffreVol.getSelectedRow()== -1){

            JOptionPane.showMessageDialog(rootPane, "vous deviez selectioné");

        }else{

             o1.setReduction(Integer.parseInt(JTextReduction.getText()));
                
                o1.setPrix(Float.parseFloat(jTextPrix.getText()));
                o1.setDate_Debut(tanggalMulai);
                o1.setDate_Fin(tanggalMulai2);
                o1.setNombrePlace(Integer.parseInt(jTextnombreplace.getText()));
                o1.setDateVol(jTextdatevol.getText());
                
                o1.setPaysDepart(jTextpaysdepart.getText());
                o1.setPaysDestination(jTextpaysdestination.getText());
                o1.setDescription(jTextdesc.getText());
                o1.setNomVol(jTextnomvol.getText());

            odao.ModifierOffreVol(o1,(int) JtableOffreVol.getValueAt(JtableOffreVol.getSelectedRow(),0));

            reset();
            UpdateOffreVol();

        }
    }//GEN-LAST:event_ModifierVolActionPerformed

    private void jtfFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFilterKeyReleased

        //nklnlnlmknlknklnlk
    }//GEN-LAST:event_jtfFilterKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OffreVol_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OffreVol_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OffreVol_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OffreVol_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OffreVol_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterOffreVol;
    private javax.swing.JTextField JTextReduction;
    private javax.swing.JTable JtableOffreVol;
    private javax.swing.JButton ModifierVol;
    private javax.swing.JButton Retour;
    private javax.swing.JButton SuupprimerOffreVol;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextPrix;
    private javax.swing.JTextField jTextdatevol;
    private javax.swing.JTextField jTextdesc;
    private javax.swing.JTextField jTextnombreplace;
    private javax.swing.JTextField jTextnomvol;
    private javax.swing.JTextField jTextpaysdepart;
    private javax.swing.JTextField jTextpaysdestination;
    private javax.swing.JTextField jtfFilter;
    // End of variables declaration//GEN-END:variables
}
