/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tn.esprit.goVoyage.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import tn.esprit.goVoyage.dao.ClientDAO;
import tn.esprit.goVoyage.entite.client;
import tn.esprit.goVoyage.utils.Utilis;

//import tn.esprit.goVoyage.utils
/**
 *
 * @author user
 */
public class InscriptionClient extends javax.swing.JFrame {

    /**
     * Creates new form InscriptionClient
     */
    public InscriptionClient() {
        initComponents();

    }

    ActionListener ToMiddle = new ActionListener() {
        int pas = 10;
        int y = 0;

        public void actionPerformed(ActionEvent e) {

            if (y < 230) {
                y += 10;
                txtAge.setLocation(txtAge.getLocation().x, txtAge.getLocation().y + y);
                txtEmailClient.setLocation(txtEmailClient.getLocation().x, txtEmailClient.getLocation().y + y);
                txtPseudo.setLocation(txtPseudo.getLocation().x, txtPseudo.getLocation().y + y);

            } else if (y > 245) {
                y -= 10;

            }

        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jComboBoxSexe = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelPseudoClient = new javax.swing.JLabel();
        jLabelM2PClient = new javax.swing.JLabel();
        jLabelEmailClient = new javax.swing.JLabel();
        JBInscrireClient = new javax.swing.JButton();
        txtPseudo = new javax.swing.JTextField();
        txtEmailClient = new javax.swing.JTextField();
        jPasswordClient = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPasswordClient1 = new javax.swing.JPasswordField();
        jLabelM2PClient1 = new javax.swing.JLabel();
        jLabelEmailClient1 = new javax.swing.JLabel();
        txtEmailClient1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBottonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sexe :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 370, 60, 30);

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge);
        txtAge.setBounds(250, 320, 171, 30);

        jComboBoxSexe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        jPanel1.add(jComboBoxSexe);
        jComboBoxSexe.setBounds(250, 370, 170, 30);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Inscription");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 171, 32);

        jLabelPseudoClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPseudoClient.setText("Login :");
        jPanel1.add(jLabelPseudoClient);
        jLabelPseudoClient.setBounds(80, 130, 42, 17);

        jLabelM2PClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelM2PClient.setText("Confirm password :");
        jPanel1.add(jLabelM2PClient);
        jLabelM2PClient.setBounds(80, 210, 120, 17);

        jLabelEmailClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmailClient.setText("Confirm Email :");
        jPanel1.add(jLabelEmailClient);
        jLabelEmailClient.setBounds(80, 290, 100, 17);

        JBInscrireClient.setText("SigneIn");
        JBInscrireClient.setActionCommand("signIn");
        JBInscrireClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInscrireClientActionPerformed(evt);
            }
        });
        jPanel1.add(JBInscrireClient);
        JBInscrireClient.setBounds(170, 440, 114, 41);

        txtPseudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPseudoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPseudo);
        txtPseudo.setBounds(250, 120, 171, 30);

        txtEmailClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEmailClient);
        txtEmailClient.setBounds(250, 240, 171, 30);

        jPasswordClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordClientActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordClient);
        jPasswordClient.setBounds(250, 160, 171, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Age :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 330, 50, 17);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 460, 50);

        jPasswordClient1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordClient1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordClient1);
        jPasswordClient1.setBounds(250, 200, 171, 30);

        jLabelM2PClient1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelM2PClient1.setText("Password :");
        jPanel1.add(jLabelM2PClient1);
        jLabelM2PClient1.setBounds(80, 170, 67, 17);

        jLabelEmailClient1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmailClient1.setText("Email :");
        jPanel1.add(jLabelEmailClient1);
        jLabelEmailClient1.setBounds(80, 250, 60, 17);

        txtEmailClient1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEmailClient1);
        txtEmailClient1.setBounds(250, 280, 171, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 478, 537);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jBottonLogin.setText("LogIn");
        jBottonLogin.setActionCommand("");
        jBottonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBottonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jBottonLogin);
        jBottonLogin.setBounds(190, 460, 59, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(476, 0, 420, 537);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBInscrireClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInscrireClientActionPerformed
        ClientDAO clientdao = new ClientDAO();

        if (txtPseudo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Saisir votre login !", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            if (jPasswordClient.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Saisir votre login !", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                if (txtPseudo.getText().equals("")) {
                } else {
                    if (txtPseudo.getText().equals("")) {
                    } else {
                        if (txtPseudo.getText().equals("")) {
                        } else {
                        }
                    }
                }
            }
        }

        if (txtPseudo.getText().equals("") || jPasswordClient.getText().equals("") || txtEmailClient.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "champs vides !", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else if (!Utilis.isValid(txtEmailClient.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Email invalide!", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
//        else if ((clientdao.chercherClientLogin(txtPseudo.getText()) != null) || !Utilis.isValid(txtEmailClient.getText())) {
//            JOptionPane.showMessageDialog(rootPane, "Login already exist!", "Erreur", JOptionPane.ERROR_MESSAGE);
//
//        }
        else {

            client client1 = new client();

            client1.setLogin(txtPseudo.getText());
//            client1.setMotDePasse(jPasswordClient.getText());
            client1.setEmail(txtEmailClient.getText());
//            client1.setAge(Integer.parseInt(txtAge.getText()));
            client1.setSexe(jComboBoxSexe.getSelectedItem().toString());
            clientdao.ajouterClient(client1);
            HomePageClient home = new HomePageClient(clientdao.chercherClientLoginPassword(client1.getLogin(), client1.getPassword()));
            home.jLabelNomClient.setText(txtPseudo.getText());

            home.setVisible(true);
        }

       //JOptionPane.showMessageDialog(rootPane, "inscription done ");

    }//GEN-LAST:event_JBInscrireClientActionPerformed

    private void jPasswordClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordClientActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void jBottonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBottonLoginActionPerformed
        ClientDAO clientlgin = new ClientDAO();
        String sql = "select * from user where login =? and motDePasse=?";


    }//GEN-LAST:event_jBottonLoginActionPerformed

    private void txtPseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPseudoActionPerformed

    private void jPasswordClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordClient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordClient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBInscrireClient;
    private javax.swing.JButton jBottonLogin;
    public javax.swing.JComboBox jComboBoxSexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmailClient;
    private javax.swing.JLabel jLabelEmailClient1;
    private javax.swing.JLabel jLabelM2PClient;
    private javax.swing.JLabel jLabelM2PClient1;
    private javax.swing.JLabel jLabelPseudoClient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPasswordField jPasswordClient;
    public javax.swing.JPasswordField jPasswordClient1;
    public javax.swing.JTextField txtAge;
    public javax.swing.JTextField txtEmailClient;
    public javax.swing.JTextField txtEmailClient1;
    public javax.swing.JTextField txtPseudo;
    // End of variables declaration//GEN-END:variables
}
